services:
  - type: web
    name: image-analyzer-app
    env: python
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt"
    startCommand: "python src/main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        sync: false
    plan: free


